version: "3"

volumes:
  geoserver-data:
  portainer_data:

services:
  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    build:
      context: .
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
        JAVA_HOME: ${JAVA_HOME}
        GS_VERSION: ${GS_VERSION}
        WAR_URL: ${WAR_URL}
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
      - "8443:8443"
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - ACTIVATE_ALL_STABLE_EXTENTIONS=${ACTIVATE_ALL_STABLE_EXTENTIONS}
      - ACTIVATE_ALL_COMMUNITY_EXTENTIONS=${ACTIVATE_ALL_COMMUNITY_EXTENTIONS}
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
