version: '2.1'

volumes:
   db-backups:
   geoserver-data:
   geo-db-data:

services:


   geoserver:
      image: kartoza/geoserver:2.16.0
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env



